import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";

import { SessionProvider } from "next-auth/react";

import Navbar from "@/components/Navbar";
import LenisWrapper from "@/components/wrapper/LenisWrapper";
import PaypalWrapper from "@/components/wrapper/PaypalWrapper";

import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist",
});
const geistMono = Geist_Mono({
    subsets: ["latin"],
    variable: "--font-geist-mono",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <Script
                    crossOrigin="anonymous"
                    src="//unpkg.com/react-scan/dist/auto.global.js"
                />
            </head>
            <body
                className={`${geist.className} ${geistMono.variable} antialiased`}
            >
                <SessionProvider>
                    <PaypalWrapper>
                        <LenisWrapper>
                            <main className="h-[150vh]">
                                <Navbar />
                                <main className="mt-16">{children}</main>
                            </main>
                        </LenisWrapper>
                    </PaypalWrapper>
                </SessionProvider>
            </body>
        </html>
    );
}
