import type { Metadata } from "next";

import { SessionProvider } from "next-auth/react";

import "./globals.css";

import Link from "next/link";
import PaypalWrapper from "@/components/wrapper/PaypalWrapper";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <SessionProvider>
                    <PaypalWrapper>
                        <main className="h-[150vh]">
                            <Navbar />
                            <main className="mt-16">{children}</main>
                        </main>
                    </PaypalWrapper>
                </SessionProvider>
            </body>
        </html>
    );
}
