import type { Metadata } from "next";

import { SessionProvider } from "next-auth/react";

import "./globals.css";

import Link from "next/link";
import PaypalWrapper from "@/components/wrapper/PaypalWrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <SessionProvider>
                    <PaypalWrapper>
                        <nav>
                            <ul>
                                <li>
                                    <Link href="/">server</Link>
                                </li>
                                <li>
                                    <Link href="/client">client</Link>
                                </li>
                            </ul>
                        </nav>
                        {children}
                    </PaypalWrapper>
                </SessionProvider>
            </body>
        </html>
    );
}
